[profile.Concurrent]
max_concurrent_tests = 16
max_concurrent_compilations = 8

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts=node_modules/@chainlink/contracts",
    "forge-std/=lib/forge-std/src/",
]